Repository jenkinsci/extension-filter-plugin, pull requests merged in 2024-02, with the labels that each got.

#57 Add spotless
  pom.xml
  src/main/java/org/jenkinsci/plugins/ConfigurableExtensionFilter.java
  src/main/java/org/jenkinsci/plugins/Exclusion.java
  src/test/java/org/jenkinsci/plugins/ConfigurableExtensionFilterTest.java
  src/test/java/org/jenkinsci/plugins/ConfigurationAsCodeTest.java
Labels: skip-changelog

#58 Add .git-blame-ignore-revs
  .git-blame-ignore-revs
Labels: skip-changelog

#60 Resolve default value breaking empty context form round trip
  src/main/resources/org/jenkinsci/plugins/ConfigurableExtensionFilter/global.jelly
  src/test/java/org/jenkinsci/plugins/ConfigurableExtensionFilterTest.java
Labels: bug

#64 Modernize Extension and avoid Guice circular dependency
  pom.xml
  src/main/java/org/jenkinsci/plugins/ConfigurableExtensionFilter.java
  src/test/java/org/jenkinsci/plugins/ConfigurableExtensionFilterTest.java
  src/test/java/org/jenkinsci/plugins/ExclusionTest.java
Labels: enhancement, developer
